+ module purge
+ '[' purge == load ']'
++ /usr/bin/modulecmd bash purge
+ eval
+ '[' purge == load ']'
+ module load anaconda/py3
+ '[' load == load ']'
+ /usr/bin/modulecmd bash list -l
+ tail -n +3
+ cut '-d ' -f1
++ /usr/bin/modulecmd bash load anaconda/py3
                                                                 
                                                                                
##############################################                                  
INFORMATION                                                                     
##############################################                                  
                                                                                
You have loaded the base anaconda environment. For specialized environments,    
you must first enable them with `source activate [env]`.                        
                                                                                
For a full list of environments, type `conda env list`                          
  
+ eval INCLUDE=/packages/7x/anaconda3/5.3.0/include ';export' 'INCLUDE;INFOPATH=/packages/7x/anaconda3/5.3.0/share/info' ';export' 'INFOPATH;LD_LIBRARY_PATH=/packages/7x/anaconda3/5.3.0/lib' ';export' 'LD_LIBRARY_PATH;LOADEDMODULES=anaconda/py3' ';export' 'LOADEDMODULES;MANPATH=/packages/7x/anaconda3/5.3.0/share/man:/usr/share/man:/usr/local/share/man' ';export' 'MANPATH;PATH=/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts/:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin' ';export' 'PATH;_LMFILES_=/usr/share/Modules/modulefiles/anaconda/py3' ';export' '_LMFILES_;unset' 'MODULEBUILDRC;unset' 'PERL5LIB;unset' 'PERL_LOCAL_LIB_ROOT;unset' 'PERL_MB_OPT;unset' 'PERL_MM_OPT;'
++ INCLUDE=/packages/7x/anaconda3/5.3.0/include
++ export INCLUDE
++ INFOPATH=/packages/7x/anaconda3/5.3.0/share/info
++ export INFOPATH
++ LD_LIBRARY_PATH=/packages/7x/anaconda3/5.3.0/lib
++ export LD_LIBRARY_PATH
++ LOADEDMODULES=anaconda/py3
++ export LOADEDMODULES
++ MANPATH=/packages/7x/anaconda3/5.3.0/share/man:/usr/share/man:/usr/local/share/man
++ export MANPATH
++ PATH=/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts/:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin
++ export PATH
++ _LMFILES_=/usr/share/Modules/modulefiles/anaconda/py3
++ export _LMFILES_
++ unset MODULEBUILDRC
++ unset PERL5LIB
++ unset PERL_LOCAL_LIB_ROOT
++ unset PERL_MB_OPT
++ unset PERL_MM_OPT
+ '[' load == load ']'
+ /usr/bin/modulecmd bash list -l
+ tail -n +3
+ cut '-d ' -f1
+ diff -c /tmp/ejakupov-prelist /tmp/ejakupov-postlist
+ grep --color=auto '^+'
+ sed 's/^+ //'
++ cat /tmp/ejakupov-difflist
+ for bobsyeruncle_module_xxx in '$(cat /tmp/${USER}-difflist)'
+ /packages/sysadmin/environment_modules/database/module_db.py load anaconda/py3
+ /bin/rm -f /tmp/ejakupov-prelist
+ /bin/rm -f /tmp/ejakupov-postlist
+ /bin/rm -f /tmp/ejakupov-difflist
+ /packages/sysadmin/slurm_scripts/module.py
+ module load hdf5/1.10.1-gnu-stock-openmpi-3.0.0
+ '[' load == load ']'
+ /usr/bin/modulecmd bash list -l
+ tail -n +3
+ cut '-d ' -f1
++ /usr/bin/modulecmd bash load hdf5/1.10.1-gnu-stock-openmpi-3.0.0


##############################################
INFORMATION
##############################################

OpenMPI uses mpirun or mpiexec by default.

To use srun, you must include the --mpi=pmi2 option.

(e.g. srun --mpi=pmi2 ./executable)

See the manpages for mpirun and srun for more
information (e.g. man srun).


+ eval HDF5_DIR=/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock ';export' 'HDF5_DIR;INCLUDE=/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/include:/packages/7x/szip/2.1/include:/packages/7x/zlib/1.2.8/include:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/include:/packages/7x/hwloc/1.11.8/include:/packages/7x/anaconda3/5.3.0/include' ';export' 'INCLUDE;INFOPATH=/packages/7x/zlib/1.2.8/share/info:/packages/7x/anaconda3/5.3.0/share/info' ';export' 'INFOPATH;JAVA_HOME=/packages/7x/java/8u162' ';export' 'JAVA_HOME;LD_LIBRARY_PATH=/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/lib:/packages/7x/szip/2.1/lib:/packages/7x/zlib/1.2.8/lib:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/lib:/packages/7x/hwloc/1.11.8/lib:/packages/7x/anaconda3/5.3.0/lib' ';export' 'LD_LIBRARY_PATH;LOADEDMODULES=anaconda/py3:java/latest:hwloc/1.11.8:openmpi/3.0.0-gnu-stock:zlib/1.2.8:szip/2.1:hdf5/1.10.1-gnu-stock-openmpi-3.0.0' ';export' 'LOADEDMODULES;MANPATH=/packages/7x/zlib/1.2.8/share/man:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/share/man:/packages/7x/hwloc/1.11.8/share/man:/packages/7x/java/8u162/man:/packages/7x/anaconda3/5.3.0/share/man:/usr/share/man:/usr/local/share/man' ';export' 'MANPATH;PATH=/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts/:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin' ';export' 'PATH;ZLIBCFLAGS=\' -I/packages/7x/zlib/1.2.8/include ';export' 'ZLIBCFLAGS;ZLIBLDFLAGS=\' -L/packages/7x/zlib/1.2.8/lib ';export' 'ZLIBLDFLAGS;_LMFILES_=/usr/share/Modules/modulefiles/anaconda/py3:/usr/share/Modules/modulefiles/java/latest:/usr/share/Modules/modulefiles/hwloc/1.11.8:/usr/share/Modules/modulefiles/openmpi/3.0.0-gnu-stock:/usr/share/Modules/modulefiles/zlib/1.2.8:/usr/share/Modules/modulefiles/szip/2.1:/usr/share/Modules/modulefiles/hdf5/1.10.1-gnu-stock-openmpi-3.0.0' ';export' '_LMFILES_;'
++ HDF5_DIR=/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock
++ export HDF5_DIR
++ INCLUDE=/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/include:/packages/7x/szip/2.1/include:/packages/7x/zlib/1.2.8/include:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/include:/packages/7x/hwloc/1.11.8/include:/packages/7x/anaconda3/5.3.0/include
++ export INCLUDE
++ INFOPATH=/packages/7x/zlib/1.2.8/share/info:/packages/7x/anaconda3/5.3.0/share/info
++ export INFOPATH
++ JAVA_HOME=/packages/7x/java/8u162
++ export JAVA_HOME
++ LD_LIBRARY_PATH=/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/lib:/packages/7x/szip/2.1/lib:/packages/7x/zlib/1.2.8/lib:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/lib:/packages/7x/hwloc/1.11.8/lib:/packages/7x/anaconda3/5.3.0/lib
++ export LD_LIBRARY_PATH
++ LOADEDMODULES=anaconda/py3:java/latest:hwloc/1.11.8:openmpi/3.0.0-gnu-stock:zlib/1.2.8:szip/2.1:hdf5/1.10.1-gnu-stock-openmpi-3.0.0
++ export LOADEDMODULES
++ MANPATH=/packages/7x/zlib/1.2.8/share/man:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/share/man:/packages/7x/hwloc/1.11.8/share/man:/packages/7x/java/8u162/man:/packages/7x/anaconda3/5.3.0/share/man:/usr/share/man:/usr/local/share/man
++ export MANPATH
++ PATH=/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts/:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin
++ export PATH
++ ZLIBCFLAGS=' -I/packages/7x/zlib/1.2.8/include'
++ export ZLIBCFLAGS
++ ZLIBLDFLAGS=' -L/packages/7x/zlib/1.2.8/lib'
++ export ZLIBLDFLAGS
++ _LMFILES_=/usr/share/Modules/modulefiles/anaconda/py3:/usr/share/Modules/modulefiles/java/latest:/usr/share/Modules/modulefiles/hwloc/1.11.8:/usr/share/Modules/modulefiles/openmpi/3.0.0-gnu-stock:/usr/share/Modules/modulefiles/zlib/1.2.8:/usr/share/Modules/modulefiles/szip/2.1:/usr/share/Modules/modulefiles/hdf5/1.10.1-gnu-stock-openmpi-3.0.0
++ export _LMFILES_
+ '[' load == load ']'
+ /usr/bin/modulecmd bash list -l
+ tail -n +3
+ cut '-d ' -f1
+ diff -c /tmp/ejakupov-prelist /tmp/ejakupov-postlist
+ grep --color=auto '^+'
+ sed 's/^+ //'
++ cat /tmp/ejakupov-difflist
+ for bobsyeruncle_module_xxx in '$(cat /tmp/${USER}-difflist)'
+ /packages/sysadmin/environment_modules/database/module_db.py load java/latest
+ for bobsyeruncle_module_xxx in '$(cat /tmp/${USER}-difflist)'
+ /packages/sysadmin/environment_modules/database/module_db.py load hwloc/1.11.8
+ for bobsyeruncle_module_xxx in '$(cat /tmp/${USER}-difflist)'
+ /packages/sysadmin/environment_modules/database/module_db.py load openmpi/3.0.0-gnu-stock
+ for bobsyeruncle_module_xxx in '$(cat /tmp/${USER}-difflist)'
+ /packages/sysadmin/environment_modules/database/module_db.py load zlib/1.2.8
+ for bobsyeruncle_module_xxx in '$(cat /tmp/${USER}-difflist)'
+ /packages/sysadmin/environment_modules/database/module_db.py load szip/2.1
+ for bobsyeruncle_module_xxx in '$(cat /tmp/${USER}-difflist)'
+ /packages/sysadmin/environment_modules/database/module_db.py load hdf5/1.10.1-gnu-stock-openmpi-3.0.0
+ /bin/rm -f /tmp/ejakupov-prelist
+ /bin/rm -f /tmp/ejakupov-postlist
+ /bin/rm -f /tmp/ejakupov-difflist
+ /packages/sysadmin/slurm_scripts/module.py
+ source activate mda2
++ _CONDA_ROOT=/packages/7x/anaconda3/5.3.0
++ . /packages/7x/anaconda3/5.3.0/etc/profile.d/conda.sh
+++ export CONDA_EXE=/packages/7x/anaconda3/5.3.0/bin/conda
+++ CONDA_EXE=/packages/7x/anaconda3/5.3.0/bin/conda
+++ export _CE_M=
+++ _CE_M=
+++ export _CE_CONDA=
+++ _CE_CONDA=
+++ export CONDA_PYTHON_EXE=/packages/7x/anaconda3/5.3.0/bin/python
+++ CONDA_PYTHON_EXE=/packages/7x/anaconda3/5.3.0/bin/python
+++ '[' -z '' ']'
+++ export CONDA_SHLVL=0
+++ CONDA_SHLVL=0
+++ '[' -n x ']'
+++ '[' -n '' ']'
+++++ dirname /packages/7x/anaconda3/5.3.0/bin/conda
++++ dirname /packages/7x/anaconda3/5.3.0/bin
+++ PATH=/packages/7x/anaconda3/5.3.0/condabin:/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts/:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin
+++ export PATH
+++ '[' -z '' ']'
+++ PS1=
++ conda activate mda2
++ '[' 2 -lt 1 ']'
++ local cmd=activate
++ shift
++ case "$cmd" in
++ __conda_activate activate mda2
++ '[' -n '' ']'
++ local cmd=activate
++ shift
++ local ask_conda
++ OLDPATH=/packages/7x/anaconda3/5.3.0/condabin:/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts/:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin
++ __add_sys_prefix_to_path
++ '[' -n '' ']'
+++ dirname /packages/7x/anaconda3/5.3.0/bin/conda
++ SYSP=/packages/7x/anaconda3/5.3.0/bin
+++ dirname /packages/7x/anaconda3/5.3.0/bin
++ SYSP=/packages/7x/anaconda3/5.3.0
++ '[' -n '' ']'
++ PATH=/packages/7x/anaconda3/5.3.0/bin:/packages/7x/anaconda3/5.3.0/condabin:/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts/:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin
++ export PATH
+++ PS1=
+++ /packages/7x/anaconda3/5.3.0/bin/conda shell.posix activate mda2
++ ask_conda='PS1='\''(mda2) '\''
export PATH='\''/home/ejakupov/.conda/envs/mda2/bin:/packages/7x/anaconda3/5.3.0/condabin:/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin'\''
export CONDA_PREFIX='\''/home/ejakupov/.conda/envs/mda2'\''
export CONDA_SHLVL='\''1'\''
export CONDA_DEFAULT_ENV='\''mda2'\''
export CONDA_PROMPT_MODIFIER='\''(mda2) '\''
export CONDA_EXE='\''/packages/7x/anaconda3/5.3.0/bin/conda'\''
export _CE_M='\'''\''
export _CE_CONDA='\'''\''
export CONDA_PYTHON_EXE='\''/packages/7x/anaconda3/5.3.0/bin/python'\'''
++ PATH=/packages/7x/anaconda3/5.3.0/condabin:/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts/:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin
++ eval 'PS1='\''(mda2) '\''
export PATH='\''/home/ejakupov/.conda/envs/mda2/bin:/packages/7x/anaconda3/5.3.0/condabin:/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin'\''
export CONDA_PREFIX='\''/home/ejakupov/.conda/envs/mda2'\''
export CONDA_SHLVL='\''1'\''
export CONDA_DEFAULT_ENV='\''mda2'\''
export CONDA_PROMPT_MODIFIER='\''(mda2) '\''
export CONDA_EXE='\''/packages/7x/anaconda3/5.3.0/bin/conda'\''
export _CE_M='\'''\''
export _CE_CONDA='\'''\''
export CONDA_PYTHON_EXE='\''/packages/7x/anaconda3/5.3.0/bin/python'\'''
+++ PS1='(mda2) '
+++ export PATH=/home/ejakupov/.conda/envs/mda2/bin:/packages/7x/anaconda3/5.3.0/condabin:/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin
+++ PATH=/home/ejakupov/.conda/envs/mda2/bin:/packages/7x/anaconda3/5.3.0/condabin:/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin
+++ export CONDA_PREFIX=/home/ejakupov/.conda/envs/mda2
+++ CONDA_PREFIX=/home/ejakupov/.conda/envs/mda2
+++ export CONDA_SHLVL=1
+++ CONDA_SHLVL=1
+++ export CONDA_DEFAULT_ENV=mda2
+++ CONDA_DEFAULT_ENV=mda2
+++ export 'CONDA_PROMPT_MODIFIER=(mda2) '
+++ CONDA_PROMPT_MODIFIER='(mda2) '
+++ export CONDA_EXE=/packages/7x/anaconda3/5.3.0/bin/conda
+++ CONDA_EXE=/packages/7x/anaconda3/5.3.0/bin/conda
+++ export _CE_M=
+++ _CE_M=
+++ export _CE_CONDA=
+++ _CE_CONDA=
+++ export CONDA_PYTHON_EXE=/packages/7x/anaconda3/5.3.0/bin/python
+++ CONDA_PYTHON_EXE=/packages/7x/anaconda3/5.3.0/bin/python
++ __conda_hashr
++ '[' -n '' ']'
++ '[' -n '' ']'
++ hash -r
+ testdir=/scratch/ejakupov/Agave/temp/8318469
+ export OMP_NUM_THREADS=1
+ OMP_NUM_THREADS=1
+ mpiexec -n 42 python -W ignore /scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py /scratch/ejakupov/Agave/temp/8318469/YiiP_system.pdb /scratch/ejakupov/Agave/temp/8318469/YiiP_system_9ns_center100x_contiguous.h5md run_1/2node_1
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 208, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/contiguous/memory/scripts/benchmark.py", line 48, in benchmark
    u.transfer_to_memory(start=start, stop=stop, step=1)
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/core/universe.py", line 626, in transfer_to_memory
    group['position/value'].read_direct(coordinates, source_sel=np.s_[start:stop])
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't convert from size to size_i)
Exception ignored in: <function ReaderBase.__del__ at 0x2ad1b0b50940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ad44a743940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2b5ff74a0940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b64f0e8e940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2b605ada7940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b43109cf940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2aee3a504940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ae833a79940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b1142e92940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ade764b3940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b9553237940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b01989af940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2adfe836b940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2adc97c80940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2b5822b18940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2b9f7db2c940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b631a25f940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b8a41a84940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ac372536940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ae473c0d940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2afb3053c940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b9cc2892940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b57c6e84940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b35241ac940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2adfaf607940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b68e4357940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ad2d3922940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b1f08ea4940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b0e4f3c9940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ae45e3b7940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b069e425940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2afcf6204940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2abe411bb940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b9404f68940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b0b0b86f940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b63339d7940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2adee262c940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b439d03f940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b9d7d2a5940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2aeab12e8940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2b5681687940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2ab82cb09940>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[25725,1],10]
  Exit code:    1
--------------------------------------------------------------------------
+ rm -r /scratch/ejakupov/Agave/temp/8318469
