+ module purge
+ '[' purge == load ']'
++ /usr/bin/modulecmd bash purge
+ eval
+ '[' purge == load ']'
+ module load anaconda/py3
+ '[' load == load ']'
+ /usr/bin/modulecmd bash list -l
+ tail -n +3
+ cut '-d ' -f1
++ /usr/bin/modulecmd bash load anaconda/py3
                                                                 
                                                                                
##############################################                                  
INFORMATION                                                                     
##############################################                                  
                                                                                
You have loaded the base anaconda environment. For specialized environments,    
you must first enable them with `source activate [env]`.                        
                                                                                
For a full list of environments, type `conda env list`                          
  
+ eval INCLUDE=/packages/7x/anaconda3/5.3.0/include ';export' 'INCLUDE;INFOPATH=/packages/7x/anaconda3/5.3.0/share/info' ';export' 'INFOPATH;LD_LIBRARY_PATH=/packages/7x/anaconda3/5.3.0/lib' ';export' 'LD_LIBRARY_PATH;LOADEDMODULES=anaconda/py3' ';export' 'LOADEDMODULES;MANPATH=/packages/7x/anaconda3/5.3.0/share/man:/usr/share/man:/usr/local/share/man' ';export' 'MANPATH;PATH=/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts/:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin' ';export' 'PATH;_LMFILES_=/usr/share/Modules/modulefiles/anaconda/py3' ';export' '_LMFILES_;unset' 'MODULEBUILDRC;unset' 'PERL5LIB;unset' 'PERL_LOCAL_LIB_ROOT;unset' 'PERL_MB_OPT;unset' 'PERL_MM_OPT;'
++ INCLUDE=/packages/7x/anaconda3/5.3.0/include
++ export INCLUDE
++ INFOPATH=/packages/7x/anaconda3/5.3.0/share/info
++ export INFOPATH
++ LD_LIBRARY_PATH=/packages/7x/anaconda3/5.3.0/lib
++ export LD_LIBRARY_PATH
++ LOADEDMODULES=anaconda/py3
++ export LOADEDMODULES
++ MANPATH=/packages/7x/anaconda3/5.3.0/share/man:/usr/share/man:/usr/local/share/man
++ export MANPATH
++ PATH=/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts/:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin
++ export PATH
++ _LMFILES_=/usr/share/Modules/modulefiles/anaconda/py3
++ export _LMFILES_
++ unset MODULEBUILDRC
++ unset PERL5LIB
++ unset PERL_LOCAL_LIB_ROOT
++ unset PERL_MB_OPT
++ unset PERL_MM_OPT
+ '[' load == load ']'
+ /usr/bin/modulecmd bash list -l
+ tail -n +3
+ cut '-d ' -f1
+ diff -c /tmp/ejakupov-prelist /tmp/ejakupov-postlist
+ grep --color=auto '^+'
+ sed 's/^+ //'
++ cat /tmp/ejakupov-difflist
+ for bobsyeruncle_module_xxx in '$(cat /tmp/${USER}-difflist)'
+ /packages/sysadmin/environment_modules/database/module_db.py load anaconda/py3
+ /bin/rm -f /tmp/ejakupov-prelist
+ /bin/rm -f /tmp/ejakupov-postlist
+ /bin/rm -f /tmp/ejakupov-difflist
+ /packages/sysadmin/slurm_scripts/module.py
+ module load hdf5/1.10.1-gnu-stock-openmpi-3.0.0
+ '[' load == load ']'
+ /usr/bin/modulecmd bash list -l
+ tail -n +3
+ cut '-d ' -f1
++ /usr/bin/modulecmd bash load hdf5/1.10.1-gnu-stock-openmpi-3.0.0


##############################################
INFORMATION
##############################################

OpenMPI uses mpirun or mpiexec by default.

To use srun, you must include the --mpi=pmi2 option.

(e.g. srun --mpi=pmi2 ./executable)

See the manpages for mpirun and srun for more
information (e.g. man srun).


+ eval HDF5_DIR=/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock ';export' 'HDF5_DIR;INCLUDE=/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/include:/packages/7x/szip/2.1/include:/packages/7x/zlib/1.2.8/include:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/include:/packages/7x/hwloc/1.11.8/include:/packages/7x/anaconda3/5.3.0/include' ';export' 'INCLUDE;INFOPATH=/packages/7x/zlib/1.2.8/share/info:/packages/7x/anaconda3/5.3.0/share/info' ';export' 'INFOPATH;JAVA_HOME=/packages/7x/java/8u162' ';export' 'JAVA_HOME;LD_LIBRARY_PATH=/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/lib:/packages/7x/szip/2.1/lib:/packages/7x/zlib/1.2.8/lib:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/lib:/packages/7x/hwloc/1.11.8/lib:/packages/7x/anaconda3/5.3.0/lib' ';export' 'LD_LIBRARY_PATH;LOADEDMODULES=anaconda/py3:java/latest:hwloc/1.11.8:openmpi/3.0.0-gnu-stock:zlib/1.2.8:szip/2.1:hdf5/1.10.1-gnu-stock-openmpi-3.0.0' ';export' 'LOADEDMODULES;MANPATH=/packages/7x/zlib/1.2.8/share/man:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/share/man:/packages/7x/hwloc/1.11.8/share/man:/packages/7x/java/8u162/man:/packages/7x/anaconda3/5.3.0/share/man:/usr/share/man:/usr/local/share/man' ';export' 'MANPATH;PATH=/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts/:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin' ';export' 'PATH;ZLIBCFLAGS=\' -I/packages/7x/zlib/1.2.8/include ';export' 'ZLIBCFLAGS;ZLIBLDFLAGS=\' -L/packages/7x/zlib/1.2.8/lib ';export' 'ZLIBLDFLAGS;_LMFILES_=/usr/share/Modules/modulefiles/anaconda/py3:/usr/share/Modules/modulefiles/java/latest:/usr/share/Modules/modulefiles/hwloc/1.11.8:/usr/share/Modules/modulefiles/openmpi/3.0.0-gnu-stock:/usr/share/Modules/modulefiles/zlib/1.2.8:/usr/share/Modules/modulefiles/szip/2.1:/usr/share/Modules/modulefiles/hdf5/1.10.1-gnu-stock-openmpi-3.0.0' ';export' '_LMFILES_;'
++ HDF5_DIR=/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock
++ export HDF5_DIR
++ INCLUDE=/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/include:/packages/7x/szip/2.1/include:/packages/7x/zlib/1.2.8/include:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/include:/packages/7x/hwloc/1.11.8/include:/packages/7x/anaconda3/5.3.0/include
++ export INCLUDE
++ INFOPATH=/packages/7x/zlib/1.2.8/share/info:/packages/7x/anaconda3/5.3.0/share/info
++ export INFOPATH
++ JAVA_HOME=/packages/7x/java/8u162
++ export JAVA_HOME
++ LD_LIBRARY_PATH=/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/lib:/packages/7x/szip/2.1/lib:/packages/7x/zlib/1.2.8/lib:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/lib:/packages/7x/hwloc/1.11.8/lib:/packages/7x/anaconda3/5.3.0/lib
++ export LD_LIBRARY_PATH
++ LOADEDMODULES=anaconda/py3:java/latest:hwloc/1.11.8:openmpi/3.0.0-gnu-stock:zlib/1.2.8:szip/2.1:hdf5/1.10.1-gnu-stock-openmpi-3.0.0
++ export LOADEDMODULES
++ MANPATH=/packages/7x/zlib/1.2.8/share/man:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/share/man:/packages/7x/hwloc/1.11.8/share/man:/packages/7x/java/8u162/man:/packages/7x/anaconda3/5.3.0/share/man:/usr/share/man:/usr/local/share/man
++ export MANPATH
++ PATH=/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts/:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin
++ export PATH
++ ZLIBCFLAGS=' -I/packages/7x/zlib/1.2.8/include'
++ export ZLIBCFLAGS
++ ZLIBLDFLAGS=' -L/packages/7x/zlib/1.2.8/lib'
++ export ZLIBLDFLAGS
++ _LMFILES_=/usr/share/Modules/modulefiles/anaconda/py3:/usr/share/Modules/modulefiles/java/latest:/usr/share/Modules/modulefiles/hwloc/1.11.8:/usr/share/Modules/modulefiles/openmpi/3.0.0-gnu-stock:/usr/share/Modules/modulefiles/zlib/1.2.8:/usr/share/Modules/modulefiles/szip/2.1:/usr/share/Modules/modulefiles/hdf5/1.10.1-gnu-stock-openmpi-3.0.0
++ export _LMFILES_
+ '[' load == load ']'
+ /usr/bin/modulecmd bash list -l
+ tail -n +3
+ cut '-d ' -f1
+ diff -c /tmp/ejakupov-prelist /tmp/ejakupov-postlist
+ grep --color=auto '^+'
+ sed 's/^+ //'
++ cat /tmp/ejakupov-difflist
+ for bobsyeruncle_module_xxx in '$(cat /tmp/${USER}-difflist)'
+ /packages/sysadmin/environment_modules/database/module_db.py load java/latest
+ for bobsyeruncle_module_xxx in '$(cat /tmp/${USER}-difflist)'
+ /packages/sysadmin/environment_modules/database/module_db.py load hwloc/1.11.8
+ for bobsyeruncle_module_xxx in '$(cat /tmp/${USER}-difflist)'
+ /packages/sysadmin/environment_modules/database/module_db.py load openmpi/3.0.0-gnu-stock
+ for bobsyeruncle_module_xxx in '$(cat /tmp/${USER}-difflist)'
+ /packages/sysadmin/environment_modules/database/module_db.py load zlib/1.2.8
+ for bobsyeruncle_module_xxx in '$(cat /tmp/${USER}-difflist)'
+ /packages/sysadmin/environment_modules/database/module_db.py load szip/2.1
+ for bobsyeruncle_module_xxx in '$(cat /tmp/${USER}-difflist)'
+ /packages/sysadmin/environment_modules/database/module_db.py load hdf5/1.10.1-gnu-stock-openmpi-3.0.0
+ /bin/rm -f /tmp/ejakupov-prelist
+ /bin/rm -f /tmp/ejakupov-postlist
+ /bin/rm -f /tmp/ejakupov-difflist
+ /packages/sysadmin/slurm_scripts/module.py
+ source activate mda2
++ _CONDA_ROOT=/packages/7x/anaconda3/5.3.0
++ . /packages/7x/anaconda3/5.3.0/etc/profile.d/conda.sh
+++ export CONDA_EXE=/packages/7x/anaconda3/5.3.0/bin/conda
+++ CONDA_EXE=/packages/7x/anaconda3/5.3.0/bin/conda
+++ export _CE_M=
+++ _CE_M=
+++ export _CE_CONDA=
+++ _CE_CONDA=
+++ export CONDA_PYTHON_EXE=/packages/7x/anaconda3/5.3.0/bin/python
+++ CONDA_PYTHON_EXE=/packages/7x/anaconda3/5.3.0/bin/python
+++ '[' -z '' ']'
+++ export CONDA_SHLVL=0
+++ CONDA_SHLVL=0
+++ '[' -n x ']'
+++ '[' -n '' ']'
+++++ dirname /packages/7x/anaconda3/5.3.0/bin/conda
++++ dirname /packages/7x/anaconda3/5.3.0/bin
+++ PATH=/packages/7x/anaconda3/5.3.0/condabin:/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts/:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin
+++ export PATH
+++ '[' -z '' ']'
+++ PS1=
++ conda activate mda2
++ '[' 2 -lt 1 ']'
++ local cmd=activate
++ shift
++ case "$cmd" in
++ __conda_activate activate mda2
++ '[' -n '' ']'
++ local cmd=activate
++ shift
++ local ask_conda
++ OLDPATH=/packages/7x/anaconda3/5.3.0/condabin:/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts/:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin
++ __add_sys_prefix_to_path
++ '[' -n '' ']'
+++ dirname /packages/7x/anaconda3/5.3.0/bin/conda
++ SYSP=/packages/7x/anaconda3/5.3.0/bin
+++ dirname /packages/7x/anaconda3/5.3.0/bin
++ SYSP=/packages/7x/anaconda3/5.3.0
++ '[' -n '' ']'
++ PATH=/packages/7x/anaconda3/5.3.0/bin:/packages/7x/anaconda3/5.3.0/condabin:/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts/:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin
++ export PATH
+++ PS1=
+++ /packages/7x/anaconda3/5.3.0/bin/conda shell.posix activate mda2
++ ask_conda='PS1='\''(mda2) '\''
export PATH='\''/home/ejakupov/.conda/envs/mda2/bin:/packages/7x/anaconda3/5.3.0/condabin:/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin'\''
export CONDA_PREFIX='\''/home/ejakupov/.conda/envs/mda2'\''
export CONDA_SHLVL='\''1'\''
export CONDA_DEFAULT_ENV='\''mda2'\''
export CONDA_PROMPT_MODIFIER='\''(mda2) '\''
export CONDA_EXE='\''/packages/7x/anaconda3/5.3.0/bin/conda'\''
export _CE_M='\'''\''
export _CE_CONDA='\'''\''
export CONDA_PYTHON_EXE='\''/packages/7x/anaconda3/5.3.0/bin/python'\'''
++ PATH=/packages/7x/anaconda3/5.3.0/condabin:/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts/:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin
++ eval 'PS1='\''(mda2) '\''
export PATH='\''/home/ejakupov/.conda/envs/mda2/bin:/packages/7x/anaconda3/5.3.0/condabin:/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin'\''
export CONDA_PREFIX='\''/home/ejakupov/.conda/envs/mda2'\''
export CONDA_SHLVL='\''1'\''
export CONDA_DEFAULT_ENV='\''mda2'\''
export CONDA_PROMPT_MODIFIER='\''(mda2) '\''
export CONDA_EXE='\''/packages/7x/anaconda3/5.3.0/bin/conda'\''
export _CE_M='\'''\''
export _CE_CONDA='\'''\''
export CONDA_PYTHON_EXE='\''/packages/7x/anaconda3/5.3.0/bin/python'\'''
+++ PS1='(mda2) '
+++ export PATH=/home/ejakupov/.conda/envs/mda2/bin:/packages/7x/anaconda3/5.3.0/condabin:/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin
+++ PATH=/home/ejakupov/.conda/envs/mda2/bin:/packages/7x/anaconda3/5.3.0/condabin:/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin
+++ export CONDA_PREFIX=/home/ejakupov/.conda/envs/mda2
+++ CONDA_PREFIX=/home/ejakupov/.conda/envs/mda2
+++ export CONDA_SHLVL=1
+++ CONDA_SHLVL=1
+++ export CONDA_DEFAULT_ENV=mda2
+++ CONDA_DEFAULT_ENV=mda2
+++ export 'CONDA_PROMPT_MODIFIER=(mda2) '
+++ CONDA_PROMPT_MODIFIER='(mda2) '
+++ export CONDA_EXE=/packages/7x/anaconda3/5.3.0/bin/conda
+++ CONDA_EXE=/packages/7x/anaconda3/5.3.0/bin/conda
+++ export _CE_M=
+++ _CE_M=
+++ export _CE_CONDA=
+++ _CE_CONDA=
+++ export CONDA_PYTHON_EXE=/packages/7x/anaconda3/5.3.0/bin/python
+++ CONDA_PYTHON_EXE=/packages/7x/anaconda3/5.3.0/bin/python
++ __conda_hashr
++ '[' -n '' ']'
++ '[' -n '' ']'
++ hash -r
+ testdir=/scratch/ejakupov/Agave/temp/6870886
+ export OMP_NUM_THREADS=1
+ OMP_NUM_THREADS=1
+ mpiexec -n 56 python -W ignore /scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py /scratch/ejakupov/Agave/temp/6870886/YiiP_system.pdb /scratch/ejakupov/Agave/temp/6870886/YiiP_system_9ns_center100x.h5md trial_1/2node_1
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2ab1e28b5790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2b10e09d8790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2aab5d1c1790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2b536f8f9790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2b72ad6d7790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2ae931844790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2b55f82d5790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2b6de3e8f790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2b8043d2c790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2ace68a55790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2b535566d790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2b1bd134f790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2b4026230790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1608 is out of bounds for axis 0 with size 1608
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2b139e89a790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2ab679aa8790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2b91b867d790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2ac459bb1790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1608 is out of bounds for axis 0 with size 1608
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2ad7db02c790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2b9522f5c790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2b1da414c790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2b9aeb040790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2b11db564790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2ba209903790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2ad53ce22790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2b6de2c7f790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2b104b3b9790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1608 is out of bounds for axis 0 with size 1608
Exception ignored in: <function ReaderBase.__del__ at 0x2ba47b8e7790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2b593b789790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2ac821c9e790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2abfae681790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2b3095252790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2aadea3f4790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2b7d175bd790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2b39aa28d790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b27f7f6f790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2b03e43c4790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1608 is out of bounds for axis 0 with size 1608
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2b6a50b29790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2b6b4f5a7790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2ba4b7665790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2b89f9bb3790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2b2b77b3b790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b0b33ba9790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b28ba04d790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2ad6fd6be790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2b19fcf80790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2b63af3ad790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2b22aba23790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b1a82f59790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b21ac5c1790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2b553e540790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2b3aeadc5790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2b5b037ed790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2b33fbc0e790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <function ReaderBase.__del__ at 0x2ab4613e3790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2b5ee447e790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/scratch/ejakupov/Agave/benchmarks/masked_array_1/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(CA.positions, x_ref, superposition=True)
IndexError: index 1609 is out of bounds for axis 0 with size 1609
Exception ignored in: <function ReaderBase.__del__ at 0x2b718d3a6790>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 696, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[23503,1],46]
  Exit code:    1
--------------------------------------------------------------------------
+ rm -r /scratch/ejakupov/Agave/temp/6870886
